"""empty message

Revision ID: 78e0e8412c88
Revises: 9cd718d4bbb8
Create Date: 2026-10-02 22:02:17.037863

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '78e0e8412c88'
down_revision: Union[str, Sequence[str], None] = '9cd718d4bbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
