"""empty message

Revision ID: 67042a6b060d
Revises: 78e0e8412c88
Create Date: 2026-10-06 22:31:10.024786

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '67042a6b060d'
down_revision: str | Sequence[str] | None = '78e0e8412c88'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_key_recipients_user_id_fkey'), 'chat_key_recipients', type_='foreignkey')
    op.create_foreign_key(None, 'chat_key_recipients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_keys_chat_id_fkey'), 'chat_keys', type_='foreignkey')
    op.create_foreign_key(None, 'chat_keys', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_user_association_chat_id_fkey'), 'chat_user_association', type_='foreignkey')
    op.drop_constraint(op.f('chat_user_association_user_id_fkey'), 'chat_user_association', type_='foreignkey')
    op.create_foreign_key(None, 'chat_user_association', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_user_association', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chats_owner_id_fkey'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_owner_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_owner_id_fkey'), 'messages', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_owner_id_fkey'), 'chats', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'chat_user_association', type_='foreignkey')
    op.drop_constraint(None, 'chat_user_association', type_='foreignkey')
    op.create_foreign_key(op.f('chat_user_association_user_id_fkey'), 'chat_user_association', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('chat_user_association_chat_id_fkey'), 'chat_user_association', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chat_keys', type_='foreignkey')
    op.create_foreign_key(op.f('chat_keys_chat_id_fkey'), 'chat_keys', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chat_key_recipients', type_='foreignkey')
    op.create_foreign_key(op.f('chat_key_recipients_user_id_fkey'), 'chat_key_recipients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
